{"level":"ERROR","location":"[get_call:143] fyersModel","message":{"API":"/profile","Error":{"s":"error","code":-8,"message":"Your token has expired. Please generate a token"}},"timestamp":"2025-01-17 11:14:21,495+0530","service":"FyersAPI","taskName":"Task-2"}
{"level":"ERROR","location":"[get_call:161] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ANIFTY2511623250CE&resolution=1&date_format=1&range_from=2025-01-07&range_to=2025-01-18&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000019E44460B90>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-01-17 12:42:52,531+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:161] fyersModel","message":{"API":"/quotes","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/quotes?symbols=NSE%3ANIFTYBANK-INDEX (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000019B60A3C410>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-01-17 18:25:10,099+0530","service":"FyersAPI","taskName":"Task-802"}
{"level":"ERROR","location":"[get_call:161] fyersModel","message":{"API":"/quotes","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/quotes?symbols=NSE%3ANIFTY50-INDEX (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000019B60A3C7D0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-01-17 18:25:15,537+0530","service":"FyersAPI","taskName":"Task-804"}
{"level":"ERROR","location":"[get_call:161] fyersModel","message":{"API":"/quotes","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/quotes?symbols=NSE%3ANIFTY50-INDEX (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000019B60A3E490>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-01-17 18:25:19,096+0530","service":"FyersAPI","taskName":"Task-805"}
