{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[WinError 10054] An existing connection was forcibly closed by the remote host","timestamp":"2025-01-16 14:34:21,864+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[WinError 10054] An existing connection was forcibly closed by the remote host","timestamp":"2025-01-16 16:57:19,845+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"Connection to remote host was lost.","timestamp":"2025-01-16 17:04:32,649+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[WinError 10054] An existing connection was forcibly closed by the remote host","timestamp":"2025-01-16 17:05:08,308+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[WinError 10054] An existing connection was forcibly closed by the remote host","timestamp":"2025-01-16 22:06:01,788+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[WinError 10054] An existing connection was forcibly closed by the remote host","timestamp":"2025-01-16 22:06:09,708+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[WinError 10054] An existing connection was forcibly closed by the remote host","timestamp":"2025-01-17 12:42:13,866+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[Errno 11001] getaddrinfo failed","timestamp":"2025-01-17 12:42:18,873+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[Errno 11001] getaddrinfo failed","timestamp":"2025-01-17 12:42:23,876+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[Errno 11001] getaddrinfo failed","timestamp":"2025-01-17 12:42:28,878+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[Errno 11001] getaddrinfo failed","timestamp":"2025-01-17 12:42:33,881+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[Errno 11001] getaddrinfo failed","timestamp":"2025-01-17 12:42:38,884+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"Connection to remote host was lost.","timestamp":"2025-01-17 17:18:11,137+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[WinError 10054] An existing connection was forcibly closed by the remote host","timestamp":"2025-01-17 18:14:55,740+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[Errno 11001] getaddrinfo failed","timestamp":"2025-01-17 18:15:00,746+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[Errno 11001] getaddrinfo failed","timestamp":"2025-01-17 18:15:05,749+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[Errno 11001] getaddrinfo failed","timestamp":"2025-01-17 18:15:10,757+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[Errno 11001] getaddrinfo failed","timestamp":"2025-01-17 18:15:15,760+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[Errno 11001] getaddrinfo failed","timestamp":"2025-01-17 18:15:20,764+0530","service":"FyersDataSocket"}
